<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.7" />
    <PackageVersion Include="MongoDB.Driver" Version="3.4.2" />
    <PackageVersion Include="DotNetCore.CAP" Version="8.3.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.7" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
  </ItemGroup>
</Project>